//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Course_Project.Info
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ТрансмашEntities1 : DbContext
    {
        public ТрансмашEntities1()
            : base("name=ТрансмашEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Materials> Materials { get; set; }
        public virtual DbSet<Month> Month { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Templates> Templates { get; set; }
        public virtual DbSet<TOrders> TOrders { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Warehouse> Warehouse { get; set; }
        public virtual DbSet<Work_Areas> Work_Areas { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
        public virtual DbSet<General_order> General_order { get; set; }
        public virtual DbSet<Order_view> Order_view { get; set; }
        public virtual DbSet<Purchase_view> Purchase_view { get; set; }
    }
}
