//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Course_Project.Info
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_view
    {
        public int idMat { get; set; }
        public Nullable<int> Material_num { get; set; }
        public string Unit_m { get; set; }
        public string Title { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
    }
}
