//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Course_Project.Info
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOrders
    {
        public int id { get; set; }
        public int Temp_num { get; set; }
        public int Material_num { get; set; }
        public int Quantity { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual Templates Templates { get; set; }
    }
}
