//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Course_Project.Info
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int idUsers { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<int> id_area { get; set; }
    
        public virtual Work_Areas Work_Areas { get; set; }
    }
}
