//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Course_Project.Info
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        public int id { get; set; }
        public int Material_cod { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Materials Materials { get; set; }
    }
}
